### ISSUE TITLE
Why use PECL trader ext anyway?

### ISSUE THREAD

**Issue by sandervanhooft** [LupeCode/phpTraderNative#6]
Hi @jb-lopez,

I've been wrestling with the original PECL trader extension for a while (install/docs/usage) before I came across this package - 🙏.

If functionality across packages is equal, what other reason could one have to keep on using the PECL extension? Performance perhaps?

**Comment by jb-lopez** [comment]
Hi @sandervanhooft,

Thank you for the inquiry.

Performance would be the reason to use the PECL package, everything else is equal since this package is a simple conversion of the C code to PHP code.

In my benchmarks at best takes 5 times longer and at worst 30 times longer.

I have not done any optimization of the PHP code yet, so those numbers could be improved. However, the compiled code of the PECL extension will always be faster.

**Comment by sandervanhooft** [comment]
Hi @jb-lopez thanks for clearing that up! May be a good addition to the readme?

**Comment by jb-lopez** [comment]
Forgot to close this issue when I added a note to the readme.

Note added in d613e34
